<a href="https://colab.research.google.com/github/ealsk/Undergrad-DeepLearning-20Fall/blob/master/01_1_NeuralNetwork_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

입력 층 (input layer)

In [2]:
X = np.array([1.0, 0.5])

In [3]:
X.shape

(2,)

In [4]:
X

array([1. , 0.5])

입력의 2개가 다음 layer에 있는 3개와 연결

In [6]:
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

In [7]:
W1.shape

(2, 3)

In [8]:
W1

array([[0.1, 0.3, 0.5],
       [0.2, 0.4, 0.6]])

곱해보기

In [10]:
a1 = np.dot(X, W1)

In [11]:
a1.shape

(3,)

In [12]:
a1

array([0.2, 0.5, 0.8])

**Q. 다음의 결과는? 그 결과의 의미는?**

In [13]:
1.0 * 0.1 + 0.5 * 0.2

0.2

의미: 1.0과 0.1을 곱한 값인 0.1, 0.5와 0.2를 곱한 값인 0.1을 합하여 0.2라는 숫자가 도출

간단한 Forward 연산 해보기

In [15]:
b1 = np.array([0.1, 0.2, 0.3])

In [17]:
a1 = np.dot(X, W1) + b1

In [18]:
print(a1)

[0.3 0.7 1.1]


numpy 의 dot 이해하기

In [19]:
x1 = np.array([[1, 2 ], [3, 4]])
x2 = np.array([[5, 6 ], [7, 8]])

In [20]:
print(x1)

[[1 2]
 [3 4]]


In [21]:
print(x2)

[[5 6]
 [7 8]]


In [22]:
x1.shape

(2, 2)

In [23]:
x2.shape

(2, 2)

In [24]:
np.dot(x1, x2)

array([[19, 22],
       [43, 50]])

In [25]:
x1 = np.array([[1, 2 ]])
x2 = np.array([[5, 6 ], [7, 8]])

In [26]:
x1.shape

(1, 2)

In [27]:
x2.shape

(2, 2)

In [28]:
np.dot(x1, x2)

array([[19, 22]])