<a href="https://colab.research.google.com/github/ealsk/Undergrad-DeepLearning-20Fall/blob/master/02_Softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([0.3, 0.9, 5.0])

In [3]:
a = np.array([0.3, -0.9, 5.0])

In [4]:
a

array([ 0.3, -0.9,  5. ])

In [5]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [6]:
y = softmax(a)

In [7]:
print(y)

[0.0089889 0.0027074 0.9883037]


In [8]:
np.sum(y)

1.0

**Numerically stable Softmax**

In [9]:
a = np.array([1010, 1000, 990])

In [10]:
y = softmax(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [11]:
print(y)

[nan nan nan]


In [12]:
def stable_softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = sum(np.exp(a-c))
    y = exp_a/sum_exp_a
    return y

In [13]:
y = stable_softmax(a)

In [14]:
print(y)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [15]:
np.sum(y)

1.0