<a href="https://colab.research.google.com/github/ealsk/Undergrad-DeepLearning-20Fall/blob/master/03_HelloNumpy_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Stack**

In [2]:
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])

세로로 쌓기

In [3]:
c= np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print(c.shape)

(2, 4)


가로로 쌓기

In [5]:
d= np.hstack((a,b))
print(d)

[1 2 3 4 5 6 7 8]


In [6]:
d.shape

(8,)

###zeros_like & ones_like

In [7]:
np.zeros_like(c)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
np.ones_like(c)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])