<a href="https://colab.research.google.com/github/ealsk/Undergrad-DeepLearning-20Fall/blob/master/04_3_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pylab as plt

In [ ]:
def function_2(x):
    if x.ndim ==1:
        return np.sum(x**2)
    else:
        return np.sum(x**2, axis=0)

In [ ]:
def numerical_gradient_single_point(f,x, verbose=False):
    h = 1e-4
    grad = np.zeros_like(x)
    print('x.size={}'.format(x.size))

    for idx in range(x.size):
        v_keep = x[idx]

        x[idx] = float(v_keep) + h
        fxh1 = f(x)
        if verbose:
            print(x, '-->', fxh1)

        x[idx] = float(v_keep) - h
        fxh2 = f(x)
        if verbose:
            print(x, '-->', fxh2)

        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = v_keep

        if verbose:
            print( 'grad [{}] = {}'. format (idx, grad [idx]))
            print()

    return grad


In [ ]:
def numerical_gradient(f, X):
    if X.ndim == 1:
        return numerical_gradient_single_point(f, X)
    else:
        grad = np.zeros_like(X)
        for idx, x in enumerate(X):
            grad[idx] = numerical_gradient_single_point(f, x)
            return grad


In [ ]:
def gradient_descent(f, init_x, lr = 0.1, step_num=100, verbose= False):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f,x)
        if verbose:
            print(x, grad)
        x -= lr * grad

    return x

In [ ]:
init_x = np.array([-3.0, 4.0])

In [ ]:
x_final =gradient_descent(function_2, init_x = init_x, lr = 0.1 )

x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2


In [ ]:
x_final

array([-8.10452420e-11,  1.08060323e-10])

###**TODO 1**


In [ ]:
x_final =gradient_descent(function_2, init_x = init_x, lr = 10.0 )

x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2


In [ ]:
x_final

array([-1.29863664e+13,  1.28237547e+13])

In [ ]:
x_final =gradient_descent(function_2, init_x = init_x, lr = 0.0001 )

x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2
x.size=2


In [ ]:
x_final

array([-1.29863664e+13,  1.28237547e+13])

lr 값을 작게 줄수록 변화를 하지 않기 때문에 원하는 값에 도달할 수 없다.

###**TODO 2**


3차원 공간에서의 좌표 궤적 그리기
(lr= 0.001, 0.01, 0.1, 1, 10)